### ISSUE TITLE
error: validator.isNull is not a function

### ISSUE THREAD

**Issue by thinkingmik** [thinkingmik/ideman#9]
In the `paramChecker.js` file at the `checkParamMixed` method 

`if (nullable === true && validator.isNull(text)) {`

should be: 

`if (nullable === true && validator.isEmpty(text)) {`

**Comment by thinkingmik** [comment]
fixed in v1.3.1

**Comment by kingsleykbc** [comment]
what ?

**Comment by thinkingmik** [comment]
Related to this issue: https://github.com/chriso/validator.js/issues/505

**Comment by rhohenester** [comment]
Nice! It works for me!
